#!/usr/bin/env bash

set -e

apt-get update
apt-get upgrade -y

apt-get install wget unzip -y

mkdir -p /opt/urt/

wget -O /opt/urt/server.tar.gz 'https://objects.dreamhost.com:443/urt/urt4.2.023.tar.gz'

mkdir -p /tmp/urtserver/
unzip /opt/urt/server.tar.gz -d /tmp/urtserver/

mv /tmp/urtserver/UrbanTerror42/ /opt/urt/urtserver
rm -rf /tmp/urtserver
mv /opt/urt/server.cfg /opt/urt/urtserver/q3ut4/server.cfg

useradd -M -d /opt/urt/ -s /bin/false -U urtserver
chown -R urtserver:urtserver /opt/urt

cat >/etc/init/urtserver.conf <<EOF
description "urban terror server"
author "Jon Chen"

setuid urtserver
setgid urtserver

start on filesystem and net-device-up IFACE=eth0
respawn

exec /opt/urt/urtserver/Quake3-UrT-Ded.x86_64
EOF

start urtserver
